name: Build clippyfi
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/mitjaimmonen/clippyfi:latest .
          docker push ghcr.io/mitjaimmonen/clippyfi:latest
